---
#
# Ansible managed
#
repository:
  description: Update cache for yum and apt package managers.
  homepage: https://buluma.github.io/
  topics: updatepackagecache, ansible, molecule, tox, playbook, hacktoberfest
